-- ============================================================
-- Database Cleanup Script
-- Drops all tables, types, procedures, functions, and sequences
-- ============================================================

SET ECHO ON;
SET FEEDBACK ON;

-- Drop Tables
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE BOOKING';
  DBMS_OUTPUT.PUT_LINE('✓ Dropped table BOOKING');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE EVENTLOCATION';
  DBMS_OUTPUT.PUT_LINE('✓ Dropped table EVENTLOCATION');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SETUPTEAM';
  DBMS_OUTPUT.PUT_LINE('✓ Dropped table SETUPTEAM');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DEPOT';
  DBMS_OUTPUT.PUT_LINE('✓ Dropped table DEPOT');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CUSTOMER';
  DBMS_OUTPUT.PUT_LINE('✓ Dropped table CUSTOMER');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- Drop Procedures
BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE POPULATEDATABASE';
  DBMS_OUTPUT.PUT_LINE('✓ Dropped procedure POPULATEDATABASE');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE PROC_REGISTER_CUSTOMER';
  DBMS_OUTPUT.PUT_LINE('✓ Dropped procedure PROC_REGISTER_CUSTOMER');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE PROC_ADD_BOOKING';
  DBMS_OUTPUT.PUT_LINE('✓ Dropped procedure PROC_ADD_BOOKING');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE PROC_ADD_EVENT_LOCATION';
  DBMS_OUTPUT.PUT_LINE('✓ Dropped procedure PROC_ADD_EVENT_LOCATION');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE POPULATEDEPOT';
  DBMS_OUTPUT.PUT_LINE('✓ Dropped procedure POPULATEDEPOT');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE POPULATESETUPTEAM';
  DBMS_OUTPUT.PUT_LINE('✓ Dropped procedure POPULATESETUPTEAM');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE POPULATECUSTOMER';
  DBMS_OUTPUT.PUT_LINE('✓ Dropped procedure POPULATECUSTOMER');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE POPULATEEVENTLOCATION';
  DBMS_OUTPUT.PUT_LINE('✓ Dropped procedure POPULATEEVENTLOCATION');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE POPULATEBOOKING';
  DBMS_OUTPUT.PUT_LINE('✓ Dropped procedure POPULATEBOOKING');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

-- Drop Functions
BEGIN
  EXECUTE IMMEDIATE 'DROP FUNCTION FUNC_GET_TEAM_BY_LOCATION';
  DBMS_OUTPUT.PUT_LINE('✓ Dropped function FUNC_GET_TEAM_BY_LOCATION');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

-- Drop Views
BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW VW_RANKED_LOCATIONS';
  DBMS_OUTPUT.PUT_LINE('✓ Dropped view VW_RANKED_LOCATIONS');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

-- Drop Types (with FORCE option to handle dependencies)
BEGIN
  EXECUTE IMMEDIATE 'DROP TYPE BOOKINGTY FORCE';
  DBMS_OUTPUT.PUT_LINE('✓ Dropped type BOOKINGTY');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TYPE EVENTLOCATIONTY FORCE';
  DBMS_OUTPUT.PUT_LINE('✓ Dropped type EVENTLOCATIONTY');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TYPE SETUPTEAMTY FORCE';
  DBMS_OUTPUT.PUT_LINE('✓ Dropped type SETUPTEAMTY');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TYPE MEMBERLISTTY FORCE';
  DBMS_OUTPUT.PUT_LINE('✓ Dropped type MEMBERLISTTY');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TYPE MEMBERTYTY FORCE';
  DBMS_OUTPUT.PUT_LINE('✓ Dropped type MEMBERTYTY');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TYPE CUSTOMERTYTY FORCE';
  DBMS_OUTPUT.PUT_LINE('✓ Dropped type CUSTOMERTYTY');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TYPE DEPOTTY FORCE';
  DBMS_OUTPUT.PUT_LINE('✓ Dropped type DEPOTTY');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TYPE ADDRESSTYTY FORCE';
  DBMS_OUTPUT.PUT_LINE('✓ Dropped type ADDRESSTYTY');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TYPE MUNICIPALITYLISTTY FORCE';
  DBMS_OUTPUT.PUT_LINE('✓ Dropped type MUNICIPALITYLISTTY');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

-- Drop Sequences
BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DEPOT';
  DBMS_OUTPUT.PUT_LINE('✓ Dropped sequence SEQ_DEPOT');
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

COMMIT;

BEGIN
  DBMS_OUTPUT.PUT_LINE('');
  DBMS_OUTPUT.PUT_LINE('====================================================');
  DBMS_OUTPUT.PUT_LINE('✅ Database cleanup completed successfully!');
  DBMS_OUTPUT.PUT_LINE('====================================================');
END;
/
