SET DEFINE OFF;
SET SERVEROUTPUT ON;
SET FEEDBACK ON;

PROMPT ========================================
PROMPT OPERATION 1 - REGISTER CUSTOMER
PROMPT ========================================
BEGIN
   DELETE FROM PLAN_TABLE WHERE STATEMENT_ID = 'STAGEUP_OP1_INS';
   EXECUTE IMMEDIATE 'DELETE FROM CUSTOMER WHERE TaxCode = ''CUST9001''';
   COMMIT;
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

PROMPT Step 1: EXPLAIN PLAN
EXPLAIN PLAN SET STATEMENT_ID = 'STAGEUP_OP1_INS' FOR
INSERT INTO CUSTOMER VALUES (CustomerTY('CUST9001', 'individual', 'Trace', 'One', NULL, NULL));

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE', 'STAGEUP_OP1_INS', 'ALL'));

PROMPT Step 2: RUN + OUTPUT
BEGIN
   proc_register_customer('CUST9001', '333777111', 'trace_op1@example.com', 'individual', 'Trace', 'One', NULL, NULL);
END;
/
COMMIT;

SELECT TaxCode, CustomerType, NVL(VAT, '-') AS VAT_OR_EMAIL
FROM CUSTOMER
WHERE TaxCode = 'CUST9001';
