SET DEFINE OFF;
SET SERVEROUTPUT ON;
SET FEEDBACK ON;

PROMPT ========================================
PROMPT OPERATION 2 - ADD BOOKING
PROMPT ========================================
BEGIN
   DELETE FROM PLAN_TABLE WHERE STATEMENT_ID = 'STAGEUP_OP2_INS';
   EXECUTE IMMEDIATE 'DELETE FROM BOOKING WHERE Code = ''BOOK9001''';
   COMMIT;
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

PROMPT Step 1: EXPLAIN PLAN
EXPLAIN PLAN SET STATEMENT_ID = 'STAGEUP_OP2_INS' FOR
INSERT INTO BOOKING VALUES (
    BookingTY(
        'BOOK9001',
        'W',
        1000,
        TO_DATE('2026-01-01','YYYY-MM-DD'),
        2,
        'N',
        (SELECT REF(st) FROM SETUPTEAM st WHERE st.Code = 'TEAM001'),
        (SELECT REF(el) FROM EVENTLOCATION el WHERE el.Code = 'LOC001')
    )
);
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE', 'STAGEUP_OP2_INS', 'ALL'));

PROMPT Step 2: RUN + OUTPUT
BEGIN
    proc_add_booking('BOOK9001', 'one-time', TRUNC(SYSDATE) + 30, 2, 1000, 'CUST001', 'LOC001', 'TEAM001', 'website');
END;
/
COMMIT;

SELECT Code, Type, Cost
FROM BOOKING
WHERE Code = 'BOOK9001';
