SET DEFINE OFF;
SET SERVEROUTPUT ON;
SET FEEDBACK ON;

PROMPT ========================================
PROMPT OPERATION 4 - VIEW TEAM BY LOCATION
PROMPT ========================================
BEGIN
   EXECUTE IMMEDIATE 'DROP INDEX idx_booking_bookdate';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
DELETE FROM PLAN_TABLE WHERE STATEMENT_ID IN ('STAGEUP_OP4_BEFORE', 'STAGEUP_OP4_AFTER');
COMMIT;

PROMPT Step 1: EXPLAIN PLAN (before)
EXPLAIN PLAN SET STATEMENT_ID = 'STAGEUP_OP4_BEFORE' FOR
SELECT st.Code || ' - ' || st.Name AS TeamInfo
FROM BOOKING b
JOIN SETUPTEAM st ON DEREF(b.Team).Code = st.Code
WHERE DEREF(b.EventLocation).Code = 'LOC001'
ORDER BY b.BookDate DESC
FETCH FIRST 1 ROW ONLY;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE', 'STAGEUP_OP4_BEFORE', 'ALL'));

PROMPT Step 2: OUTPUT
SELECT func_get_team_by_location('CUST001', 'LOC001') AS TeamInfo
FROM DUAL;

PROMPT Step 3: EXPLAIN PLAN (after)
CREATE INDEX idx_booking_bookdate ON BOOKING (BookDate DESC);

EXPLAIN PLAN SET STATEMENT_ID = 'STAGEUP_OP4_AFTER' FOR
SELECT st.Code || ' - ' || st.Name AS TeamInfo
FROM BOOKING b
JOIN SETUPTEAM st ON DEREF(b.Team).Code = st.Code
WHERE DEREF(b.EventLocation).Code = 'LOC001'
ORDER BY b.BookDate DESC
FETCH FIRST 1 ROW ONLY;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE', 'STAGEUP_OP4_AFTER', 'ALL'));
