SET DEFINE OFF;
SET SERVEROUTPUT ON;
SET FEEDBACK ON;

PROMPT ========================================
PROMPT OPERATION 5 - RANKED LOCATIONS
PROMPT ========================================
BEGIN
   EXECUTE IMMEDIATE 'DROP INDEX idx_booking_bookdate';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/
DELETE FROM PLAN_TABLE WHERE STATEMENT_ID IN ('STAGEUP_OP5_BEFORE', 'STAGEUP_OP5_AFTER');
COMMIT;

PROMPT Step 1: EXPLAIN PLAN (before)
EXPLAIN PLAN SET STATEMENT_ID = 'STAGEUP_OP5_BEFORE' FOR
SELECT el.Code AS LocationCode, COUNT(b.Code) AS NumBookings
FROM EVENTLOCATION el
LEFT JOIN BOOKING b
    ON DEREF(b.EventLocation).Code = el.Code
GROUP BY el.Code
ORDER BY NumBookings DESC, el.Code;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE', 'STAGEUP_OP5_BEFORE', 'ALL'));

PROMPT Step 2: EXPLAIN PLAN (after)
CREATE INDEX idx_booking_bookdate ON BOOKING (BookDate DESC);

EXPLAIN PLAN SET STATEMENT_ID = 'STAGEUP_OP5_AFTER' FOR
SELECT el.Code AS LocationCode, COUNT(b.Code) AS NumBookings
FROM EVENTLOCATION el
LEFT JOIN BOOKING b
    ON DEREF(b.EventLocation).Code = el.Code
GROUP BY el.Code
ORDER BY NumBookings DESC, el.Code;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE', 'STAGEUP_OP5_AFTER', 'ALL'));

PROMPT Step 3: OUTPUT
SELECT el.Code AS LocationCode, COUNT(b.Code) AS NumBookings
FROM EVENTLOCATION el
LEFT JOIN BOOKING b
    ON DEREF(b.EventLocation).Code = el.Code
GROUP BY el.Code
ORDER BY NumBookings DESC, el.Code;
